name: CI Pipeline

# Este workflow é acionado em pull requests e pushes para as branches develop e main.
on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop, main ]

# Define os jobs para o backend e frontend, garantindo que ambos sejam verificados em cada PR ou push.
jobs:
  backend-checks:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    # Passos para o job de backend: checkout do código, configuração do Node.js,
    # instalação de dependências, linting, build (verificação de tipagem) e execução de testes unitários.
    steps:
      - name: Fazer o checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js (Versão 24)
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências
        run: npm install

      - name: Executar Lint
        run: npm run lint

      - name: Executar o Build (Verificar tipagem)
        run: npm run build

      - name: Executar Testes Unitários
        run: npm test

  frontend-checks:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    # Passos para o job de frontend: checkout do código, configuração do Node.js,
    # instalação de dependências, criação de um environment.ts para o CI, linting e build (verificação de tipagem e sintaxe).
    steps:
      - name: Fazer o checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js (Versão 24)
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependências
        run: npm install

      - name: Criar environment.ts para o CI
        run: |
          mkdir -p src/environments
          echo "export const environment = { production: true, apiUrl: 'https://api-falsa.com', supabaseUrl: 'https://db-falsa.supabase.co', supabaseKey: 'chave-falsa' };" > src/environments/environment.ts

      - name: Executar Lint
        run: npm run lint

      - name: Executar o Build Angular (Verifica tipagem e sintaxe)
        run: npm run build
